hub: add management command to filter failed tasks impacted by OSH-362
openscanhub/openscanhub pull request #184
Opened 2023-11-15 07:02 UTC by rhyw

Usage:

    python3 osh/hub/manage.py find_failed_tasks

2023-11-15 07:02 UTC, rhyw commented
This is a one-time helper command. I assume we don't need it to be merged.

2023-11-15 07:56 UTC, jperezdealgaba commented on osh/hub/scan/management/commands/find_failed_tasks.py
> +CSMOCK_VERSION = "csmock-3.5.0.20231018.081735.gf8bfc23.internal-1"
Although this is a one time command, wouldn't it be better to not be tied to a specific version of csmock?

2023-11-15 11:21 UTC, lzaoral requested changes
As agreed with @kdudka, this feature is directly tied to your specific and private deployment of OpenScanHub and is **not applicable** to OpenScanHub in general.  Therefore, the upstream repository is not the right place for such changes.

edit: typo

2023-11-15 14:47 UTC, kdudka commented
Yes, this does not make any sense from upstream point of view.  https://issues.redhat.com/browse/OSH-362 is not publicly available and there is no description of what and why is being done by the changes.  Also the name `find_failed_tasks` is misleading when we are in fact looking for `CLOSED` tasks.  Let's follow up on the internal Jira issue.

2023-11-15 14:47 UTC, closed without merging

2023-11-16 03:11 UTC, rhyw commented
I'm just finding somewhere for a review of whether the filter is doing what it's supposed to. I don't have a better idea how this could be reviewed. Never mind, I also updated in the jira.