client: fix the `--hub` option
openscanhub/openscanhub pull request #238
Opened 2024-03-08 15:55 UTC by lzaoral

Previously, the code in OSH was not properly detecting the required support in `kobo`.

Fixes: 6d3e3cb3d57b0f4ca442ab919d2b6ee097032041 ("client: handle the --hub option globally")

2024-03-12 15:16 UTC, kdudka requested changes
The problem does not seem to be fully fixed.  The following command still silently ignores the `--hub` option:
```
% osh-cli watch-log --hub=https://covscan.lab.eng.brq2.redhat.com/osh/xmlrpc 467390
```
... despite the option is documented:
```
% osh-cli watch-log --help
Usage: osh-cli watch-log task_id

Options:
  -h, --help           show this help message and exit
  --username=USERNAME  specify user
  --password=PASSWORD  specify password
  --hub=HUB            specify URL of XML-RPC interface on hub
  --type=TYPE          Show log with this name, default is stdout.log
  --poll=POLL          Interval how often server should be polled for new info
                       (seconds >= 15)
  --nowait             Return after fetching current logfile, don't wait until
                       task finishes
```

2024-03-14 11:41 UTC, lzaoral commented
You have uncovered another bug, @kdudka!  The thing is that `watch-log` command does not use XML-RPC at all, so the option is silently ignored: https://github.com/release-engineering/kobo/blob/88237f21fce90b80135aeeaf20a602946c31586d/kobo/client/commands/cmd_watch_log.py#L60

Couple please try any command that is actually implemented in OSH?  That should be fixed by this PR.

2024-03-15 09:20 UTC, lzaoral commented
@kdudka FYI, https://github.com/release-engineering/kobo/pull/252 was merged.

2024-03-15 15:44 UTC, kdudka approved these changes
@lzaoral Perfect.  Thank you for fixing both the issues!

2024-03-15 15:46 UTC, merged