client: catch network connectivity exceptions when verifying builds
openscanhub/openscanhub pull request #239
Opened 2024-03-18 06:53 UTC by rhyw

Related: https://issues.redhat.com/browse/OSH-144

2024-03-18 09:32 UTC, lzaoral requested changes
This seems to be quite overcomplicated.  What about just this instead?

```diff
diff --git a/osh/client/commands/shortcuts.py b/osh/client/commands/shortcuts.py
index 990f029e..739da189 100644
--- a/osh/client/commands/shortcuts.py
+++ b/osh/client/commands/shortcuts.py
@@ -24,15 +24,10 @@ def verify_build_exists(nvr, profile):
     """
     try:
         cfg = koji.read_config(profile)
-    except koji.ConfigurationError as e:
-        print('koji:', e, file=sys.stderr)
-        return False
-
-    proxy_object = koji.ClientSession(cfg['server'])
-    try:
-        # getBuild XML-RPC call is defined here: ./hub/kojihub.py:3206
+        proxy_object = koji.ClientSession(cfg['server'])
         build = proxy_object.getBuild(nvr)
-    except koji.GenericError:
+    except Exception as e:
+        print('koji:', e, file=sys.stderr)
         return False

     if build is None:

```

2024-03-19 03:09 UTC, rhyw commented
> This seems to be quite overcomplicated. What about just this instead?
> 
I tested, this also works. The reason I use "print_traceback" is to avoid the potential exception chains raised.

2024-03-19 03:17 UTC, rhyw commented
> > This seems to be quite overcomplicated. What about just this instead?
> 
> I tested, this also works. The reason I use "print_traceback" is to avoid the potential exception chains raised.
> +    except Exception as e:
> +        print('koji:', e, file=sys.stderr)

My bad, this should only print the str repr of the exception only. I'll give some tests before updating.

2024-04-03 14:04 UTC, lzaoral approved these changes

2024-04-07 06:34 UTC, merged